[2023-11-21T17:36:08.556+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: competition.train_test_split_data manual__2023-11-21T12:34:39.836337+00:00 [queued]>
[2023-11-21T17:36:08.596+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: competition.train_test_split_data manual__2023-11-21T12:34:39.836337+00:00 [queued]>
[2023-11-21T17:36:08.597+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T17:36:08.662+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): train_test_split_data> on 2023-11-21 12:34:39.836337+00:00
[2023-11-21T17:36:08.682+0500] {standard_task_runner.py:57} INFO - Started process 21644 to run task
[2023-11-21T17:36:08.698+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'competition', 'train_test_split_data', 'manual__2023-11-21T12:34:39.836337+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/competition_score.py', '--cfg-path', '/tmp/tmpyxpnlefw']
[2023-11-21T17:36:08.709+0500] {standard_task_runner.py:85} INFO - Job 23: Subtask train_test_split_data
[2023-11-21T17:36:08.966+0500] {task_command.py:416} INFO - Running <TaskInstance: competition.train_test_split_data manual__2023-11-21T12:34:39.836337+00:00 [running]> on host Acer
[2023-11-21T17:36:09.402+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='makar' AIRFLOW_CTX_DAG_ID='competition' AIRFLOW_CTX_TASK_ID='train_test_split_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T12:34:39.836337+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T12:34:39.836337+00:00'
[2023-11-21T17:36:09.416+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-21T17:36:09.421+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/makar/MLops_3/scripts/train_test_split_data.py']
[2023-11-21T17:36:09.470+0500] {subprocess.py:86} INFO - Output:
[2023-11-21T17:36:09.737+0500] {subprocess.py:93} INFO - python3: can't open file '/home/makar/MLops_3/scripts/train_test_split_data.py': [Errno 2] No such file or directory
[2023-11-21T17:36:09.755+0500] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-21T17:36:09.820+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-21T17:36:09.837+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=competition, task_id=train_test_split_data, execution_date=20231121T123439, start_date=20231121T123608, end_date=20231121T123609
[2023-11-21T17:36:09.894+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task train_test_split_data (Bash command failed. The command returned a non-zero exit code 2.; 21644)
[2023-11-21T17:36:09.922+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:36:10.053+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
